/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ptithcm.tracnghiem.view;

import com.ptithcm.tracnghiem.model.dto.BaiThiDto;
import com.ptithcm.tracnghiem.model.dto.BoDeDto;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MINHDAT
 */
public class PnlExamQuestionNavigation extends javax.swing.JPanel {
    
    
    /**
     * Creates new form PnlExamQuestionNavigation
     */
    public PnlExamQuestionNavigation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblQuestionNav = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(314, 551));
        setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(51, 204, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DANH SÁCH CÁC CÂU HỎI TRONG BÀI THI");
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(286, 34));
        add(jLabel1, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.CardLayout());

        tblQuestionNav.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Câu số", "Đã chọn"
            }
        ));
        jScrollPane1.setViewportView(tblQuestionNav);

        jPanel1.add(jScrollPane1, "card2");

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

//    Methods
//    Lấy danh sách các lựa chọn
    public List<BaiThiDto> getDsLuaChon() {
        List<BaiThiDto> baiThiDtos = new ArrayList<>();
        DefaultTableModel model = (DefaultTableModel) tblQuestionNav.getModel();
        for (int i = 0; i < model.getRowCount(); ++i) {
            baiThiDtos.add(
                    new BaiThiDto(
                            Integer.parseInt(model.getValueAt(i, 0).toString()), 
                            Short.parseShort(model.getValueAt(i, 1).toString()), 
                            model.getValueAt(i, 2).toString())
            );
        }
        return baiThiDtos;
    }
    
//    Đổ dữ liệu vào bảng
    public void fillDataTable(List<BoDeDto> boDeDtos) {
        DefaultTableModel model = (DefaultTableModel) tblQuestionNav.getModel();
        model.setRowCount(0);
        boDeDtos.forEach(boDeDto -> {
            Object[] row = {boDeDto.getCauHoi(), boDeDto.getStt(), ""};
            model.addRow(row);
        });
    }
    
//    Getters and setters
    public JTable getTblQuestionNav() {
        return tblQuestionNav;
    }

    public void setTblQuestionNav(JTable tblQuestionNav) {
        this.tblQuestionNav = tblQuestionNav;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblQuestionNav;
    // End of variables declaration//GEN-END:variables
}
