/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ptithcm.tracnghiem.view;

import java.awt.Dimension;
import javax.swing.ButtonGroup;
import javax.swing.JRadioButton;
import javax.swing.JTextArea;

/**
 *
 * @author MINHDAT
 */
public class PnlQuestion extends javax.swing.JPanel {

    /**
     * Creates new form PnlQuestion
     */
    public PnlQuestion(String cauSo) {
        initComponents();
        setName(cauSo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupAnswer = new javax.swing.ButtonGroup();
        txtContent = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        rdA = new javax.swing.JRadioButton();
        rdB = new javax.swing.JRadioButton();
        rdC = new javax.swing.JRadioButton();
        rdD = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        txtContent.setEditable(false);
        txtContent.setBackground(new java.awt.Color(255, 255, 255));
        txtContent.setColumns(20);
        txtContent.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtContent.setLineWrap(true);
        txtContent.setTabSize(0);
        txtContent.setWrapStyleWord(true);
        txtContent.setBorder(null);
        txtContent.setPreferredSize(null);
        add(txtContent, java.awt.BorderLayout.NORTH);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(4, 1, 0, 8));

        rdA.setBackground(new java.awt.Color(255, 255, 255));
        btnGroupAnswer.add(rdA);
        rdA.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdA.setActionCommand("A");
        rdA.setName(""); // NOI18N
        rdA.setPreferredSize(null);
        jPanel1.add(rdA);

        rdB.setBackground(new java.awt.Color(255, 255, 255));
        btnGroupAnswer.add(rdB);
        rdB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdB.setActionCommand("B");
        rdB.setName(""); // NOI18N
        rdB.setPreferredSize(null);
        jPanel1.add(rdB);

        rdC.setBackground(new java.awt.Color(255, 255, 255));
        btnGroupAnswer.add(rdC);
        rdC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdC.setActionCommand("C");
        rdC.setName(""); // NOI18N
        rdC.setPreferredSize(null);
        jPanel1.add(rdC);

        rdD.setBackground(new java.awt.Color(255, 255, 255));
        btnGroupAnswer.add(rdD);
        rdD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdD.setActionCommand("D");
        rdD.setName(""); // NOI18N
        rdD.setPreferredSize(null);
        jPanel1.add(rdD);

        jPanel2.add(jPanel1, "card2");

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

//    Methods
    public String getChoice() {
        return btnGroupAnswer.getSelection().getActionCommand();
    }
    
    public void setName(String cauHoi) {
        rdA.setName(cauHoi);
        rdB.setName(cauHoi);
        rdC.setName(cauHoi);
        rdD.setName(cauHoi);
    }
    
//    Getters and setters
    public ButtonGroup getBtnGroupAnswer() {
        return btnGroupAnswer;
    }
    
    public void setBtnGroupAnswer(ButtonGroup btnGroupAnswer) {    
        this.btnGroupAnswer = btnGroupAnswer;
    }

    public JRadioButton getRdA() {
        return rdA;
    }

    public void setRdA(JRadioButton rdA) {
        this.rdA = rdA;
    }

    public JRadioButton getRdB() {
        return rdB;
    }

    public void setRdB(JRadioButton rdB) {
        this.rdB = rdB;
    }

    public JRadioButton getRdC() {
        return rdC;
    }

    public void setRdC(JRadioButton rdC) {
        this.rdC = rdC;
    }

    public JRadioButton getRdD() {
        return rdD;
    }

    public void setRdD(JRadioButton rdD) {
        this.rdD = rdD;
    }

    public JTextArea getTxtContent() {
        return txtContent;
    }

    public void setTxtContent(JTextArea txtContent) {
        this.txtContent = txtContent;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupAnswer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton rdA;
    private javax.swing.JRadioButton rdB;
    private javax.swing.JRadioButton rdC;
    private javax.swing.JRadioButton rdD;
    private javax.swing.JTextArea txtContent;
    // End of variables declaration//GEN-END:variables
}
