/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ptithcm.tracnghiem.view;

import com.microsoft.sqlserver.jdbc.SQLServerException;
import com.ptithcm.tracnghiem.entity.MonHoc;
import com.ptithcm.tracnghiem.global_variable.LoginVariables;
import com.ptithcm.tracnghiem.service.BangDiemService;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JPanel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author MINHDAT
 */
public class PnlReviewExamResultOption extends javax.swing.JPanel {
    private JPanel pnlReportSection;

    /**
     * Creates new form PnlReviewExamResultOption
     */
    public PnlReviewExamResultOption(JPanel pnlReportSection) {
        initComponents();
        fillFieldData();
        this.pnlReportSection = pnlReportSection;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtStudentCode = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cboSubjects = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cboTimes = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        btnReviewExamResult = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        jPanel3.setOpaque(false);
        jPanel3.setRequestFocusEnabled(false);
        jPanel3.setLayout(new java.awt.BorderLayout(10, 0));

        jLabel1.setText("Mã sinh viên:");
        jPanel3.add(jLabel1, java.awt.BorderLayout.WEST);

        txtStudentCode.setEditable(false);
        txtStudentCode.setPreferredSize(new java.awt.Dimension(120, 34));
        jPanel3.add(txtStudentCode, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3);

        jPanel4.setOpaque(false);
        jPanel4.setRequestFocusEnabled(false);
        jPanel4.setLayout(new java.awt.BorderLayout(10, 0));

        jLabel2.setText("Môn học:");
        jPanel4.add(jLabel2, java.awt.BorderLayout.WEST);

        cboSubjects.setEnabled(false);
        cboSubjects.setPreferredSize(new java.awt.Dimension(180, 34));
        cboSubjects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSubjectsActionPerformed(evt);
            }
        });
        jPanel4.add(cboSubjects, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel4);

        jPanel5.setOpaque(false);
        jPanel5.setRequestFocusEnabled(false);
        jPanel5.setLayout(new java.awt.BorderLayout(10, 0));

        jLabel3.setText("Lần thi:");
        jPanel5.add(jLabel3, java.awt.BorderLayout.WEST);

        cboTimes.setEnabled(false);
        cboTimes.setPreferredSize(new java.awt.Dimension(100, 34));
        cboTimes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTimesActionPerformed(evt);
            }
        });
        jPanel5.add(cboTimes, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel5);

        jScrollPane1.setViewportView(jPanel1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(150, 48));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        btnReviewExamResult.setText("Xem kết quả");
        btnReviewExamResult.setEnabled(false);
        btnReviewExamResult.setPreferredSize(new java.awt.Dimension(120, 34));
        btnReviewExamResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReviewExamResultActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel2.add(btnReviewExamResult, gridBagConstraints);

        add(jPanel2, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents

    private void cboSubjectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSubjectsActionPerformed
        try {
            DefaultComboBoxModel timesModel = new DefaultComboBoxModel();
            timesModel.addAll(BangDiemService.findAllExamTimesOfSubject(txtStudentCode.getText(), ((MonHoc) cboSubjects.getSelectedItem()).getMaMH()));
            cboTimes.setModel(timesModel);
            if (timesModel.getSize() > 0) {
                cboTimes.setSelectedIndex(0);
                cboTimes.setEnabled(true);
            }
        } catch (SQLException ex) {
            MessageBox.showErrorBox(ex.getClass().getName(), ex.getMessage());
        }
    }//GEN-LAST:event_cboSubjectsActionPerformed

    private void cboTimesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTimesActionPerformed
        btnReviewExamResult.setEnabled(true);
    }//GEN-LAST:event_cboTimesActionPerformed

    private void btnReviewExamResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReviewExamResultActionPerformed
        try {
//            Làm mới vùng chứa báo cáo
            pnlReportSection.removeAll();
            
//            Hiển thị báo cáo
            JasperDesign jasperDesign = JRXmlLoader.load(getClass().getResource("/reports/rpXemKetQuaThi.jrxml").getFile());
            JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
            
            Map<String,Object> parameters = new HashMap<>();
            parameters.put("MASV", LoginVariables.databaseConnector.getAccount().getUsername());
            parameters.put("HOTEN", LoginVariables.databaseConnector.getAccount().getFullName());
            parameters.put("MAMH", ((MonHoc) cboSubjects.getSelectedItem()).getMaMH());
            parameters.put("LAN", Short.parseShort(String.valueOf(cboTimes.getSelectedItem())));
            
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameters, LoginVariables.databaseConnector.getConnection());
            JRViewer viewer = new JRViewer(jasperPrint);
            
            pnlReportSection.add(viewer);
            pnlReportSection.revalidate();
            pnlReportSection.repaint();
        } catch (SQLServerException ex) {
            MessageBox.showErrorBox(ex.getClass().getName(), ex.getMessage());
        } catch (JRException ex) {
            MessageBox.showErrorBox(ex.getClass().getName(), ex.getMessage());
        }
    }//GEN-LAST:event_btnReviewExamResultActionPerformed

    public void fillFieldData() {
        try {
            txtStudentCode.setText(LoginVariables.databaseConnector.getAccount().getUsername());
            DefaultComboBoxModel subjectModel = new DefaultComboBoxModel();
            subjectModel.addAll(BangDiemService.findAllExamSubjects(LoginVariables.databaseConnector.getAccount().getUsername()));
            cboSubjects.setModel(subjectModel);
            if (subjectModel.getSize() > 0) {
                cboSubjects.setSelectedIndex(0);
                cboSubjects.setEnabled(true);
            }
        } catch (SQLException ex) {
            MessageBox.showErrorBox(ex.getClass().getName(), ex.getMessage());
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReviewExamResult;
    private javax.swing.JComboBox<String> cboSubjects;
    private javax.swing.JComboBox<String> cboTimes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtStudentCode;
    // End of variables declaration//GEN-END:variables
}
