/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ptithcm.tracnghiem.view;

import com.ptithcm.tracnghiem.entity.GiaoVienDangKy;
import com.ptithcm.tracnghiem.entity.Lop;
import com.ptithcm.tracnghiem.entity.MonHoc;
import com.ptithcm.tracnghiem.model.dto.ObjectAction;
import java.awt.Cursor;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author MINHDAT
 */
public class PnlTeacherRegisterInfo extends javax.swing.JPanel {
    
    /**
     * Creates new form PnlQuestionInfo
     */
    public PnlTeacherRegisterInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnResetForm = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cboTimes = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cboLevel = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cboClassroomCode = new javax.swing.JComboBox<>();
        cboSubject = new javax.swing.JComboBox<>();
        cboQuestionQuantity = new javax.swing.JComboBox<>();
        cboTime = new javax.swing.JComboBox<>();
        txtTeacherCode = new javax.swing.JTextField();
        dateTime = new com.ptithcm.tracnghiem.view.JDateTimePicker();

        setPreferredSize(new java.awt.Dimension(400, 624));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnResetForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/24x24/reset.png"))); // NOI18N
        btnResetForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetFormMouseClicked(evt);
            }
        });
        btnResetForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnResetForm.setCursor(new Cursor(Cursor.HAND_CURSOR));
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnResetForm.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            }
        });

        btnResetForm.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnResetForm.setCursor(new Cursor(Cursor.HAND_CURSOR));
            }
        });
        jPanel1.add(btnResetForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 30, 40));

        jLabel1.setBackground(new java.awt.Color(0, 0, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THÔNG TIN ĐĂNG KÝ THI CỦA GIÁO VIÊN");
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(110, 40));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, -1));

        add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel3.setPreferredSize(new java.awt.Dimension(400, 582));

        jLabel2.setText("Lần thi:");

        cboTimes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));

        jLabel3.setText("Trình độ:");

        cboLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLevelActionPerformed(evt);
            }
        });

        jLabel4.setText("Ngày thi:");

        jLabel5.setText("Môn học:");

        jLabel6.setText("Số câu thi:");

        jLabel7.setText("Thời gian thi:");

        jLabel8.setText("Gv đăng ký:");

        jLabel11.setText("Lớp:");

        cboClassroomCode.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboClassroomCodeItemStateChanged(evt);
            }
        });

        cboSubject.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboSubjectItemStateChanged(evt);
            }
        });

        cboQuestionQuantity.setEditable(true);
        cboQuestionQuantity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100" }));

        cboTime.setEditable(true);
        cboTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60" }));

        txtTeacherCode.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboClassroomCode, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(dateTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                            .addComponent(cboTimes, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(cboLevel, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGap(195, 195, 195)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cboTime, 0, 286, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cboQuestionQuantity, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtTeacherCode))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(cboClassroomCode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(cboSubject))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboTimes, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboQuestionQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboTime, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTeacherCode, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel3);

        add(jScrollPane1, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetFormMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetFormMouseClicked
        reset();
    }//GEN-LAST:event_btnResetFormMouseClicked

    private void cboClassroomCodeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboClassroomCodeItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cboClassroomCodeItemStateChanged

    private void cboSubjectItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboSubjectItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cboSubjectItemStateChanged

    private void cboLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboLevelActionPerformed

//    Methods
    public GiaoVienDangKy getGVDKData(List<ObjectAction> objectActions) {
        return new GiaoVienDangKy(
                txtTeacherCode.getText(), ((Lop) cboClassroomCode.getSelectedItem()).getMaLop(),
                ((MonHoc) cboSubject.getSelectedItem()).getMaMH(), 
                String.valueOf(cboLevel.getSelectedItem()), 
                dateTime.getDateTime().getTime(), 
                Short.parseShort(String.valueOf(cboTimes.getSelectedItem())), 
                Short.parseShort(String.valueOf(cboQuestionQuantity.getSelectedItem())), 
                Short.parseShort(String.valueOf(cboTime.getSelectedItem()))
        );
    }
    
//    Đổ dữ liệu lớp học ra combobox
    public void fillClassroomComboBox(List<Lop> lops) {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        model.addAll(lops);
        cboClassroomCode.setModel(model);
        cboClassroomCode.setSelectedIndex(0);
    }
    
//    Đổ dữ liệu môn học ra combobox
    public void fillSubjectComboBox(List<MonHoc> subjects) {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        model.addAll(subjects);
        cboSubject.setModel(model);
        cboSubject.setSelectedIndex(0);
    }
    
//    Đổ dữ liệu trình độ ra combobox
    public void fillLevelComboBox(List<String> levelList) {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        model.addAll(levelList);
        cboLevel.setModel(model);
        cboLevel.setSelectedIndex(0);
    }
    
//    Chọn  cho combobox khi biết mã mh
    public void setSelectedClassroomItem(String maLop) {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboClassroomCode.getModel();
        for (int i = 0; i < model.getSize(); ++i) {
            Lop lop = (Lop) model.getElementAt(i);
            if (lop.getMaLop().equals(maLop)) {
                cboClassroomCode.setSelectedItem(lop);
                break;
            }
        }
    }
    
//    Chọn môn học cho combobox khi biết mã mh
    public void setSelectedSubjectItem(String maMH) {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboSubject.getModel();
        for (int i = 0; i < model.getSize(); ++i) {
            MonHoc subject = (MonHoc) model.getElementAt(i);
            if (subject.getMaMH().equals(maMH)) {
                cboSubject.setSelectedItem(subject);
                break;
            }
        }
    }
    
//    Disable các trường nhập liệu là khóa chính
    public void disableComponents() {
        cboClassroomCode.setEnabled(false);
        cboSubject.setEnabled(false);
        cboTimes.setEnabled(false);
    }
    
//    Enable các trường khi reset form
    public void enableComponents() {
        cboClassroomCode.setEnabled(true);
        cboSubject.setEnabled(true);
        cboTimes.setEnabled(true);
    }
    
//    Reset lại form
    public void reset() {
        enableComponents();
        cboClassroomCode.setSelectedIndex(0);
        cboSubject.setSelectedIndex(0);
        cboTimes.setSelectedIndex(0);
        cboLevel.setSelectedIndex(0);
        dateTime.reset();
        cboQuestionQuantity.setSelectedIndex(0);
        cboTime.setSelectedIndex(0);
    }
    
//    Getters and setters
    public JComboBox<String> getCboClassroomCode() {
        return cboClassroomCode;
    }

    public void setCboClassroomCode(JComboBox<String> cboClassroomCode) {
        this.cboClassroomCode = cboClassroomCode;
    }

    public JComboBox<String> getCboLevel() {
        return cboLevel;
    }

    public void setCboLevel(JComboBox<String> cboLevel) {
        this.cboLevel = cboLevel;
    }

    public JComboBox<String> getCboQuestionQuantity() {
        return cboQuestionQuantity;
    }

    public void setCboQuestionQuantity(JComboBox<String> cboQuestionQuantity) {
        this.cboQuestionQuantity = cboQuestionQuantity;
    }

    public JComboBox<String> getCboSubject() {
        return cboSubject;
    }

    public void setCboSubject(JComboBox<String> cboSubject) {
        this.cboSubject = cboSubject;
    }

    public JComboBox<String> getCboTime() {
        return cboTime;
    }

    public void setCboTime(JComboBox<String> cboTime) {
        this.cboTime = cboTime;
    }

    public JComboBox<String> getCboTimes() {
        return cboTimes;
    }

    public void setCboTimes(JComboBox<String> cboTimes) {
        this.cboTimes = cboTimes;
    }

    public JDateTimePicker getDateTime() {
        return dateTime;
    }

    public void setDateTime(JDateTimePicker dateTime) {
        this.dateTime = dateTime;
    }

    public JTextField getTxtTeacherCode() {
        return txtTeacherCode;
    }

    public void setTxtTeacherCode(JTextField txtTeacherCode) {
        this.txtTeacherCode = txtTeacherCode;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnResetForm;
    private javax.swing.JComboBox<String> cboClassroomCode;
    private javax.swing.JComboBox<String> cboLevel;
    private javax.swing.JComboBox<String> cboQuestionQuantity;
    private javax.swing.JComboBox<String> cboSubject;
    private javax.swing.JComboBox<String> cboTime;
    private javax.swing.JComboBox<String> cboTimes;
    private com.ptithcm.tracnghiem.view.JDateTimePicker dateTime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtTeacherCode;
    // End of variables declaration//GEN-END:variables
}
